Add prometheus metrics
lab259/http-sqs-service pull request #9
Opened 2020-01-16 21:11 UTC by chicobentojr

### :sparkles: Enhancements

* Add Prometheus metrics to Send, Receive and Delete messages

2020-01-20 18:42 UTC, felipemfp approved these changes
LGTM :tada::+1:

2020-01-21 20:06 UTC, jamillosantos requested changes

2020-01-21 20:06 UTC, jamillosantos commented on collector.go
> +				Name: fmt.Sprintf("db_%smessage_calls", prefix),
I think `db_` is not a suitable prefix for these metrics. Update all of them.

2020-01-21 20:06 UTC, jamillosantos commented on service.go
>  	return nil, rscsrv.ErrServiceNotRunning
Would not this be counted as an error? Same for others, you can reply if do not agree.

2020-01-21 20:27 UTC, chicobentojr commented on service.go
>  	return nil, rscsrv.ErrServiceNotRunning
I was thinking that we can retrieve the number of `ErrServiceNotRunning`, without adding a new counter, calculating as: `messageCalls - (messageSuccess + messageFailures)`.
If we count ServiceNotRunning also as an error, we lost this possibility.

Also, I think that calling a method without starting service is a different kind of error and will be detected before.

2020-01-22 11:39 UTC, chicobentojr commented on collector.go
> +				Name: fmt.Sprintf("db_%smessage_calls", prefix),
Ok. Done :heavy_check_mark:

2020-01-22 18:31 UTC, jamillosantos requested changes
Sorry for not being clear man. When I was saying about the `db_` prefix, I really meant replacing it in favour of `sqs_` or something similar. Prefixes are your friend when dealing with metrics.

2020-01-22 23:36 UTC, merged